#!/usr/bin/env python3
"""Serve the poetry site and proxy its authenticated FLUX image requests."""

from __future__ import annotations

import argparse
import base64
import binascii
import copy
import hashlib
import io
import json
import os
import re
import secrets
import threading
import time
import wave
import weakref
from collections import OrderedDict
from concurrent.futures import ThreadPoolExecutor
from email.utils import parsedate_to_datetime
from http.client import HTTPException
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.parse import quote, unquote
from urllib.request import Request, urlopen


def load_local_environment(path: Path) -> None:
    """Load simple KEY=VALUE entries without adding a dotenv dependency."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


def load_config(path: Path) -> dict:
    """Read local service addresses from config.json so they change without code edits."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return {}


def load_books(path: Path) -> list[dict]:
    """Read the per-book narration settings so prompts are not tied to one poet."""
    try:
        return json.loads(path.read_text(encoding="utf-8")).get("books", [])
    except FileNotFoundError:
        return []


BASE_DIR = Path(__file__).resolve().parent
load_local_environment(BASE_DIR / ".env")
CONFIG = load_config(BASE_DIR / "config.json")
BOOKS = load_books(BASE_DIR / "books.json")
BOOKS_BY_ID = {str(book.get("id", "")): book for book in BOOKS if book.get("id")}
DEFAULT_BOOK = BOOKS[0] if BOOKS else {}
UPSTREAMS = CONFIG.get("upstreams", {})
FLUX_BASE_URL = os.environ.get("FLUX_BASE_URL", UPSTREAMS.get("flux", "http://192.168.6.40:2222")).rstrip("/")
VLLM_BASE_URL = os.environ.get("VLLM_BASE_URL", UPSTREAMS.get("vllm", "http://192.168.5.40:8000")).rstrip("/")
VLLM_FALLBACK_URL = os.environ.get("VLLM_FALLBACK_URL", UPSTREAMS.get("vllm_fallback", "")).rstrip("/")
TTS_BASE_URL = os.environ.get("TTS_BASE_URL", UPSTREAMS.get("tts", "http://mjbmini.local:7860")).rstrip("/")
FLUX_API_KEY = os.environ.get("FLUX_API_KEY", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
LOCAL_TTS_MODEL = "Qwen3-TTS"
DEFAULT_GEMINI_TTS_MODEL = "gemini-3.1-flash-tts-preview"
GEMINI_TTS_PIPELINE_VERSION = 2
GEMINI_TTS_MAX_OUTPUT_TOKENS = 16384
GEMINI_TTS_REQUEST_INTERVAL = 15
GEMINI_TTS_NEXT_REQUEST_AT = 0.0
GEMINI_TTS_MODELS = {
    "gemini-3.8-flash-lite-tts",
    "gemini-3.8-flash-tts",
    "gemini-3.1-flash-tts-preview",
    "gemini-2.5-flash-preview-tts",
}
# Jobs belong to the server, not to the browser connection. Keep credentials
# only in worker memory; recordings remain in the existing disk library.
TTS_JOBS = OrderedDict()
TTS_JOBS_LOCK = threading.Lock()
TTS_EXECUTOR = ThreadPoolExecutor(max_workers=4, thread_name_prefix="tts-queue")
TTS_RENDER_LOCK = threading.Lock()
LOCAL_TTS_BATCH_WORKERS = 4
LOCAL_TTS_SLOTS = threading.BoundedSemaphore(4)
TTS_KEY_LOCKS = weakref.WeakValueDictionary()
TTS_KEY_LOCKS_LOCK = threading.Lock()
TTS_FALLBACK_URL = os.environ.get("TTS_FALLBACK_URL", UPSTREAMS.get("tts_fallback", "http://192.168.6.38:7860")).rstrip("/")


class TTSGenerationError(ValueError):
    """A safe, reader-facing explanation generated by our audio validation."""


class TTSStopped(TTSGenerationError):
    """The user stopped a narration queue."""


class TTSRetryableError(TTSGenerationError):
    """An incomplete provider response that may succeed on another attempt."""

LOCAL_TTS_VOICES = tuple((name, "Qwen3 speaker") for name in (
    "serena", "vivian", "uncle_fu", "ryan", "aiden", "ono_anna", "sohee", "eric", "dylan",
))
LOCAL_TTS_VOICE_NAMES = {name for name, _ in LOCAL_TTS_VOICES}
DEFAULT_TTS_VOICES = {"feminine": "vivian", "masculine": "ryan", "companion": "aiden"}

GEMINI_TTS_VOICES = {"feminine": "Gacrux", "masculine": "Algieba", "companion": "Iapetus"}
GEMINI_STUDIO_VOICES = frozenset("""
Zephyr Puck Charon Kore Fenrir Leda Orus Aoede Callirrhoe Autonoe
Enceladus Iapetus Umbriel Algieba Despina Erinome Algenib Rasalgethi
Laomedeia Achernar Alnilam Schedar Gacrux Pulcherrima Achird
Zubenelgenubi Vindemiatrix Sadachbia Sadaltager Sulafat
""".split())


def resolve_gemini_voice(voice: str) -> str | None:
    return GEMINI_TTS_VOICES.get(voice) or (voice if voice in GEMINI_STUDIO_VOICES else None)


def resolve_local_voice(voice: str) -> str | None:
    name = voice.lower()
    return load_tts_voices().get(name) or (name if name in LOCAL_TTS_VOICE_NAMES else None)


def tts_provider_error(error: HTTPError, api_key: str = "") -> str:
    """Keep actionable provider messages without exposing credentials or raw bodies."""
    message = ""
    try:
        payload = json.loads(error.read())
        detail = payload.get("error", payload) if isinstance(payload, dict) else {}
        message = detail.get("message", "") if isinstance(detail, dict) else ""
        if not isinstance(message, str):
            message = ""
        if isinstance(detail, dict) and detail.get("code") == "content_blocked":
            message = "Gemini declined this passage (content_blocked): " + message
    except (ValueError, OSError):
        pass
    for secret in (api_key, GEMINI_API_KEY):
        if secret:
            message = message.replace(secret, "[redacted]")
    message = re.sub(r"AIza[\w-]+", "[redacted]", message)
    message = " ".join(message.split())[:1000]
    return f"Provider returned HTTP {error.code}" + (f": {message}" if message else ".")


VOICE_CONFIG_PATH = BASE_DIR / "voice-config.json"
VOICE_CONFIG_LOCK = threading.Lock()
# One short, identical passage for every voice, so they can be compared directly.
# The samples live apart from the reading library and are committed with the
# source: they depend on nothing local, and auditioning voices on a fresh
# checkout should not mean paying Gemini for thirty renders again.
VOICE_SAMPLE_TEXT = "Two roads diverged in a yellow wood,\nAnd sorry I could not travel both"
VOICE_SAMPLES_PATH = BASE_DIR / "voice-samples"
ALLOWED_GET_PATHS = {"/status"}
ALLOWED_POST_PATHS = {"/generate"}
ALLOWED_CHAT_GET_PATHS = {"/v1/models"}
ALLOWED_CHAT_POST_PATHS = {"/v1/chat/completions"}
CHAT_TIMEOUT = 300
# FLUX reads the prompt through T5, which has no operator for "no", so the
# prohibitions written into the positive prompt often act as attractors instead.
# SDXL takes a real negative prompt, so when that backend is loaded the exclusions
# are sent where they are actually understood. The proxy owns this text so the
# batch script and the browser both inherit it from one place.
NEGATIVE_PROMPT = (
    "nudity, nude figure, bare chest, exposed breasts, exposed genitals, topless, "
    "underwear, explicit sexual activity, pornography, graphic violence, gore, blood, "
    "two men as a romantic couple, two women as a romantic couple, "
    "text, lettering, caption, title, signature, watermark, typography, written words"
)
# A refusal is only remembered for a while: the image host restarts independently
# of this server, so a build that rejects the field can be replaced by one that
# accepts it without anything here being told.
FLUX_BACKEND_TTL = 300
FLUX_BACKEND_LOCK = threading.Lock()
FLUX_BACKEND_STATE: dict = {"sdxl": None, "checked": 0.0}
# Recent readings are kept so the player can load them from a URL ending in a
# real filename; a blob URL downloads as "download.wav" whatever the page says.
AUDIO_CACHE: "OrderedDict[str, tuple[str, bytes]]" = OrderedDict()
AUDIO_CACHE_LIMIT = 8
SAFE_FILENAME = re.compile(r"[^A-Za-z0-9 ,._'()\[\]-]+")
AUDIO_LIBRARY_PATH = BASE_DIR / "audio-library"
AUDIO_LIBRARY_LOCK = threading.Lock()
# The Miscellaneous shelf lives here rather than in one browser, so every reader
# of this server sees the same poems.
USER_POEMS_PATH = BASE_DIR / "user-poems.json"
USER_POEMS_LOCK = threading.Lock()
IMAGE_LIBRARY_PATH = BASE_DIR / "poem-images" / "manifest.json"
IMAGE_ASSETS_PATH = BASE_DIR / "poem-images" / "assets"
IMAGE_DELETIONS_PATH = BASE_DIR / "poem-images" / "deleted.json"
IMAGE_LIBRARY_LOCK = threading.Lock()


def read_user_poems() -> list[dict]:
    try:
        stored = json.loads(USER_POEMS_PATH.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return []
    except json.JSONDecodeError:
        return []
    return stored if isinstance(stored, list) else []


def write_user_poems(poems: list[dict]) -> None:
    """Write through a temporary file so a crash cannot truncate the shelf."""
    temporary = USER_POEMS_PATH.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(poems, indent=2, ensure_ascii=False), encoding="utf-8")
    temporary.replace(USER_POEMS_PATH)


def remember_flux_backend(sdxl: bool) -> None:
    with FLUX_BACKEND_LOCK:
        FLUX_BACKEND_STATE.update({"sdxl": sdxl, "checked": time.monotonic()})


def flux_supports_negative_prompt() -> bool:
    """Whether the image host will accept negative_prompt, learned by trying it.

    /status cannot answer this: it reports queue depth, power draw, and the
    vision model, but names no image backend at all, whether the host was
    started with --sdxl or without it. So the field is sent optimistically and
    the answer comes from how the host replies. A refusal is remembered and the
    generation retried without it, which costs one rejected attempt per plain
    FLUX restart; assuming the other way round costs the negative prompt
    permanently, since nothing would ever prove SDXL was there.
    """
    with FLUX_BACKEND_LOCK:
        refused = FLUX_BACKEND_STATE["sdxl"]
        if refused is False and time.monotonic() - FLUX_BACKEND_STATE["checked"] < FLUX_BACKEND_TTL:
            return False
    return True


def browser_poem_hash(title: str, content: str) -> str:
    """Match app.js stableHash, which iterates JavaScript UTF-16 code units."""
    value = f"{title}\n{content}".encode("utf-16-le")
    result = 2166136261
    for offset in range(0, len(value), 2):
        code_unit = value[offset] | (value[offset + 1] << 8)
        result = ((result ^ code_unit) * 16777619) & 0xFFFFFFFF
    return format(result, "x")


def image_poem_metadata() -> dict[str, dict]:
    metadata = {}
    for book in BOOKS:
        if book.get("poems"):
            try:
                poems = json.loads((BASE_DIR / str(book["poems"])).read_text(encoding="utf-8"))
            except (FileNotFoundError, json.JSONDecodeError):
                continue
        elif book.get("userPoems"):
            poems = read_user_poems()
        else:
            continue
        for poem in poems if isinstance(poems, list) else []:
            title, content = str(poem.get("title", "")), str(poem.get("content", ""))
            if title and content:
                metadata[browser_poem_hash(title, content)] = {
                    "poemTitle": title,
                    "collection": str(book.get("name") or book.get("title") or "Poetry collection"),
                }
    return metadata


def load_tts_voices() -> dict[str, str]:
    """The role-to-voice bindings, with anything unrecognised falling back to default."""
    try:
        with VOICE_CONFIG_LOCK:
            saved = json.loads(VOICE_CONFIG_PATH.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return dict(DEFAULT_TTS_VOICES)
    if not isinstance(saved, dict):
        return dict(DEFAULT_TTS_VOICES)
    return {
        role: saved[role] if saved.get(role) in LOCAL_TTS_VOICE_NAMES else default
        for role, default in DEFAULT_TTS_VOICES.items()
    }


def write_tts_voices(voices: dict[str, str]) -> None:
    with VOICE_CONFIG_LOCK:
        temporary = VOICE_CONFIG_PATH.with_suffix(".json.tmp")
        temporary.write_text(json.dumps(voices, indent=2) + "\n", encoding="utf-8")
        temporary.replace(VOICE_CONFIG_PATH)


def audio_library_key(
    title: str, text: str, voice: str, kind: str, book_id: str, speak_title: bool = True,
    provider: str = "local", model: str = "",
) -> str:
    """Identify the exact performance request across browsers and server restarts."""
    identity = {
        "model": model if provider == "gemini" else LOCAL_TTS_MODEL,
        "title": title,
        "text": text,
        "voice": voice,
        "kind": kind,
        "book": book_id,
    }
    # Keep the existing local-Qwen library addressable. Gemini is already
    # separated by its model name, and naming the provider makes that explicit.
    if provider == "gemini":
        identity["provider"] = provider
        # Generation settings affect whether a reading is complete. Bump this
        # when those settings change so an older, truncated render is not reused.
        identity["pipelineVersion"] = GEMINI_TTS_PIPELINE_VERSION
    if not speak_title:
        identity["speakTitle"] = False
    # The role is what the key has always carried, so a rebound role would other-
    # wise keep serving readings performed by the voice it used to point at. Name
    # the voice as well, but only once it stops being that role's default, so the
    # library built up under the defaults stays addressable.
    resolved = GEMINI_TTS_VOICES.get(voice) if provider == "gemini" else resolve_local_voice(voice)
    defaults = GEMINI_TTS_VOICES if provider == "gemini" else DEFAULT_TTS_VOICES
    if resolved and resolved != defaults.get(voice):
        identity["voiceName"] = resolved
    return hashlib.sha256(
        json.dumps(identity, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def cache_audio(filename: str, audio: bytes, key: str | None = None, metadata: dict | None = None) -> str:
    """Persist one reading and return a stable, human-named media path."""
    name = SAFE_FILENAME.sub(" ", filename).strip().strip(".")
    name = re.sub(r"\s+", " ", name)[:120] or "reading"
    if not name.lower().endswith(".wav"):
        name += ".wav"

    token = key or secrets.token_urlsafe(9)
    AUDIO_CACHE[token] = (name, audio)
    while len(AUDIO_CACHE) > AUDIO_CACHE_LIMIT:
        AUDIO_CACHE.popitem(last=False)
    if key:
        AUDIO_LIBRARY_PATH.mkdir(exist_ok=True)
        temporary = AUDIO_LIBRARY_PATH / f"{key}.tmp"
        with AUDIO_LIBRARY_LOCK:
            temporary.write_bytes(audio)
            temporary.replace(AUDIO_LIBRARY_PATH / f"{key}.wav")
            metadata_path = AUDIO_LIBRARY_PATH / f"{key}.json"
            try:
                record = json.loads(metadata_path.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                record = {}
            if not isinstance(record, dict):
                record = {}
            record.update(metadata or {})
            record['filename'] = name
            metadata_temp = metadata_path.with_suffix('.json.tmp')
            metadata_temp.write_text(json.dumps(record, ensure_ascii=False), encoding='utf-8')
            metadata_temp.replace(metadata_path)
    return f"/api/tts/audio/{token}/{quote(name)}"


def stitch_wav_files(paths: list[Path]) -> bytes:
    """Join compatible PCM WAV recordings without transcoding or quality loss."""
    if not paths:
        raise ValueError("At least one saved audio part is required.")
    parameters = None
    frames = []
    for path in paths:
        with wave.open(str(path), "rb") as source:
            current = (source.getnchannels(), source.getsampwidth(), source.getframerate(), source.getcomptype())
            if parameters is None:
                parameters = current
            elif current != parameters:
                raise ValueError("The saved parts use incompatible WAV formats.")
            frames.append(source.readframes(source.getnframes()))
    output = io.BytesIO()
    with wave.open(output, "wb") as target:
        target.setnchannels(parameters[0])
        target.setsampwidth(parameters[1])
        target.setframerate(parameters[2])
        target.setcomptype(parameters[3], "not compressed")
        target.writeframes(b"".join(frames))
    return output.getvalue()


def stitched_audio_key(part_keys: list[str]) -> str:
    identity = json.dumps({"kind": "stitched-chapter", "parts": part_keys}, separators=(",", ":"))
    return hashlib.sha256(identity.encode("utf-8")).hexdigest()


class PoetryRequestHandler(SimpleHTTPRequestHandler):
    """Static-file handler with small, allow-listed FLUX and model reverse proxies."""

    def do_HEAD(self) -> None:  # noqa: N802 - stdlib handler API
        if self.path.split('?', 1)[0] == '/library.html':
            self.path = '/index.html'
        if self.path.startswith("/api/tts/audio/"):
            self._serve_cached_audio()
            return
        super().do_HEAD()

    def do_GET(self) -> None:  # noqa: N802 - stdlib handler API
        if self.path.split('?', 1)[0] == '/library.html':
            # Both entry URLs load the same shell; history navigation keeps
            # the narration element alive instead of loading another document.
            self.path = '/index.html'
        if self.path.startswith("/api/tts/jobs/"):
            job_id = self.path.rsplit("/", 1)[-1]
            with TTS_JOBS_LOCK:
                job = TTS_JOBS.get(job_id)
                snapshot = dict(job) if job else None
            self._send_json(200 if snapshot else 404, snapshot or {"error": "Queue not found. Retry to reuse saved parts."})
            return
        if self.path.rstrip("/") == "/images":
            self.path = "/images.html"
            super().do_GET()
            return
        if self.path.rstrip("/") == "/voices":
            self.path = "/voices.html"
            super().do_GET()
            return
        if self.path == "/api/tts/voices":
            self._list_tts_voices()
            return
        if self.path == "/api/image-library":
            self._list_image_library()
            return
        if self.path.startswith("/api/flux/"):
            upstream_path = self.path.removeprefix("/api/flux")
            if upstream_path in ALLOWED_GET_PATHS or upstream_path.startswith("/images/"):
                self._proxy_flux("GET", upstream_path)
            else:
                self.send_error(404, "Unknown FLUX endpoint")
            return
        if self.path.startswith("/api/chat/"):
            upstream_path = self.path.removeprefix("/api/chat")
            if upstream_path in ALLOWED_CHAT_GET_PATHS:
                self._proxy_chat("GET", upstream_path)
            else:
                self.send_error(404, "Unknown model endpoint")
            return
        if self.path.startswith("/api/tts/audio/"):
            self._serve_cached_audio()
            return
        if self.path == "/api/poems":
            self._list_user_poems()
            return
        super().do_GET()

    def do_PUT(self) -> None:  # noqa: N802 - stdlib handler API
        if self.path == "/api/tts/roles":
            self._assign_tts_voice()
            return
        if self.path.startswith("/api/poems/"):
            self._update_user_poem(self.path.removeprefix("/api/poems/"))
            return
        self.send_error(405, "PUT is only supported for the shared shelf and narration voices")

    def do_DELETE(self) -> None:  # noqa: N802 - stdlib handler API
        if self.path == "/api/image-library":
            self._delete_library_images()
            return
        if self.path.startswith("/api/poems/"):
            self._delete_user_poem(self.path.removeprefix("/api/poems/"))
            return
        self.send_error(405, "DELETE is only supported for the shared shelf")

    @staticmethod
    def _image_manifest() -> dict:
        try:
            payload = json.loads(IMAGE_LIBRARY_PATH.read_text(encoding="utf-8"))
        except (FileNotFoundError, json.JSONDecodeError):
            return {}
        return payload if isinstance(payload, dict) else {}

    @staticmethod
    def _write_image_manifest(manifest: dict) -> None:
        IMAGE_LIBRARY_PATH.parent.mkdir(exist_ok=True)
        temporary = IMAGE_LIBRARY_PATH.with_suffix(".json.tmp")
        temporary.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        temporary.replace(IMAGE_LIBRARY_PATH)

    def _list_image_library(self) -> None:
        with IMAGE_LIBRARY_LOCK:
            manifest = self._image_manifest()
        metadata = image_poem_metadata()
        images = []
        for poem_id, records in manifest.items():
            for record in records if isinstance(records, list) else []:
                filename = str(record.get("filename", ""))
                if filename.startswith("poem-images/assets/"):
                    images.append({"poemId": poem_id, **metadata.get(poem_id, {}), **record})
        self._send_json(200, {"images": images})

    def _save_library_image(self) -> None:
        """Copy a completed FLUX image into the shared, durable image library."""
        try:
            payload = self._read_json_body()
            if not isinstance(payload, dict):
                raise ValueError('Provide an image record.')
            poem_id, filename = str(payload.get('poemId', '')), str(payload.get('filename', ''))
            if not re.fullmatch(r'[a-f0-9]{1,8}', poem_id) or not re.fullmatch(r'[A-Za-z0-9_-][A-Za-z0-9_.-]*\.(?:png|jpg|jpeg|webp)', filename, re.I):
                raise ValueError('Provide a poem identifier and an image filename.')
            identity = hashlib.sha256(f'{poem_id}:{filename}'.encode()).hexdigest()
            relative = f'poem-images/assets/{identity}{Path(filename).suffix.lower()}'
            with IMAGE_LIBRARY_LOCK:
                manifest = self._image_manifest()
                existing = next((r for r in manifest.get(poem_id, []) if r.get('filename') == relative), None)
                try:
                    deleted = json.loads(IMAGE_DELETIONS_PATH.read_text())
                except (OSError, ValueError):
                    deleted = []
                if f'image:{poem_id}:{filename}' in deleted:
                    self._send_json(200, {'deleted': True})
                    return
            if existing and (BASE_DIR / relative).is_file():
                self._send_json(200, {'image': existing})
                return
            headers = {'X-API-Key': FLUX_API_KEY or self.headers.get('X-API-Key', '')}
            request = Request(f'{FLUX_BASE_URL}/images/{quote(filename)}', headers=headers)
            with urlopen(request, timeout=30) as response:
                if not response.headers.get('Content-Type', '').startswith('image/'):
                    raise ValueError('The image server did not return an image.')
                data = response.read(32 * 1024 * 1024 + 1)
                if len(data) > 32 * 1024 * 1024:
                    raise ValueError('Image exceeds the shared library size limit.')
            record = {k: str(payload.get(k, ''))[:12000] for k in ('prompt', 'style', 'poemTitle', 'collection')}
            record.update(filename=relative, originalFilename=filename, status='done')
            with IMAGE_LIBRARY_LOCK:
                try:
                    deleted = json.loads(IMAGE_DELETIONS_PATH.read_text())
                except (OSError, ValueError):
                    deleted = []
                if f'image:{poem_id}:{filename}' in deleted:
                    self._send_json(200, {'deleted': True})
                    return
                IMAGE_ASSETS_PATH.mkdir(parents=True, exist_ok=True)
                (BASE_DIR / relative).write_bytes(data)
                manifest = self._image_manifest()
                records = manifest.setdefault(poem_id, [])
                if not any(r.get('filename') == relative for r in records):
                    records.append(record)
                self._write_image_manifest(manifest)
            self._send_json(200, {'image': record})
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {'error': str(error)})
        except (URLError, OSError) as error:
            self._send_json(502, {'error': f'Could not save shared image: {error}'})

    def _delete_library_images(self) -> None:
        try:
            requested = self._read_json_body().get("images", [])
        except json.JSONDecodeError:
            self._send_json(400, {"error": "The deletion request was not valid JSON."})
            return
        targets = {
            (str(item.get("poemId", "")), str(item.get("filename", "")))
            for item in requested if isinstance(item, dict)
        }
        if not targets:
            self._send_json(400, {"error": "Select at least one image to delete."})
            return

        deleted = []
        with IMAGE_LIBRARY_LOCK:
            manifest = self._image_manifest()
            try:
                tombstones = set(json.loads(IMAGE_DELETIONS_PATH.read_text(encoding="utf-8")))
            except (FileNotFoundError, json.JSONDecodeError, TypeError):
                tombstones = set()
            for poem_id, filename in targets:
                relative = filename.removeprefix("poem-images/assets/")
                if not filename.startswith("poem-images/assets/") or Path(relative).name != relative:
                    continue
                records = manifest.get(poem_id, [])
                for record in records:
                    if record.get('filename') == filename and record.get('originalFilename'):
                        tombstones.add(f"image:{poem_id}:{record['originalFilename']}")
                kept = [record for record in records if record.get("filename") != filename]
                if len(kept) == len(records):
                    continue
                if kept:
                    manifest[poem_id] = kept
                else:
                    manifest.pop(poem_id, None)
                try:
                    (IMAGE_ASSETS_PATH / relative).unlink()
                except FileNotFoundError:
                    pass
                deleted.append(filename)
                tombstones.add(poem_id)
            self._write_image_manifest(manifest)
            tombstone_temp = IMAGE_DELETIONS_PATH.with_suffix(".json.tmp")
            tombstone_temp.write_text(json.dumps(sorted(tombstones), indent=2) + "\n", encoding="utf-8")
            tombstone_temp.replace(IMAGE_DELETIONS_PATH)
        self._send_json(200, {"deleted": deleted})

    def _read_json_body(self) -> dict:
        length = int(self.headers.get("Content-Length", "0"))
        return json.loads(self.rfile.read(length) or b"{}")

    @staticmethod
    def _clean_poem(payload: dict) -> dict:
        """Keep the reader's line breaks, drop anything else unexpected."""
        title = re.sub(r"\s+", " ", str(payload.get("title", ""))).strip()[:200]
        content = str(payload.get("content", "")).replace("\r\n", "\n").replace("\r", "\n")
        content = re.sub(r"\n{4,}", "\n\n\n", content).strip()[:200_000]
        if not title or not content:
            raise ValueError("A title and the poem itself are both required.")

        poem = {"title": title, "content": content,
                "firstLine": next((line for line in content.split("\n") if line.strip()), "")[:100]}
        for field in ("author", "translator"):
            value = re.sub(r"\s+", " ", str(payload.get(field, ""))).strip()[:120]
            if value:
                poem[field] = value
        return poem

    def _list_user_poems(self) -> None:
        self._send_json(200, {"poems": read_user_poems()})

    def _add_user_poem(self) -> None:
        try:
            poem = self._clean_poem(self._read_json_body())
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": str(error)})
            return

        with USER_POEMS_LOCK:
            poems = read_user_poems()
            if any(item["title"] == poem["title"] and item["content"] == poem["content"]
                   for item in poems):
                self._send_json(409, {"error": "That poem is already on the shelf."})
                return
            poem["id"] = secrets.token_urlsafe(8)
            poems.append(poem)
            write_user_poems(poems)
        self._send_json(201, {"poem": poem})

    def _update_user_poem(self, poem_id: str) -> None:
        try:
            update = self._clean_poem(self._read_json_body())
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": str(error)})
            return

        with USER_POEMS_LOCK:
            poems = read_user_poems()
            position = next((i for i, item in enumerate(poems) if item.get("id") == poem_id), -1)
            if position == -1:
                self._send_json(404, {"error": "That poem is no longer on the shelf."})
                return
            if any(i != position and item["title"] == update["title"]
                   and item["content"] == update["content"] for i, item in enumerate(poems)):
                self._send_json(409, {"error": "That poem is already on the shelf."})
                return
            update["id"] = poem_id
            poems[position] = update
            write_user_poems(poems)
        self._send_json(200, {"poem": update})

    def _delete_user_poem(self, poem_id: str) -> None:
        with USER_POEMS_LOCK:
            poems = read_user_poems()
            remaining = [item for item in poems if item.get("id") != poem_id]
            if len(remaining) == len(poems):
                self._send_json(404, {"error": "That poem is no longer on the shelf."})
                return
            write_user_poems(remaining)
        self._send_json(200, {"removed": poem_id})

    def end_headers(self) -> None:  # noqa: N802 - stdlib handler API
        # Static files here change constantly. Without this browsers cache them
        # heuristically and pair a new script with last week's stylesheet.
        if not self.path.startswith("/api/"):
            self.send_header("Cache-Control", "no-cache")
        super().end_headers()

    def _serve_cached_audio(self) -> None:
        request_path, _, query = self.path.partition("?")
        parts = unquote(request_path).split("/")
        token = parts[4] if len(parts) > 4 else ""
        entry = AUDIO_CACHE.get(token)
        if not entry and re.fullmatch(r"[0-9a-f]{64}", token):
            audio_file = AUDIO_LIBRARY_PATH / f"{token}.wav"
            metadata_file = AUDIO_LIBRARY_PATH / f"{token}.json"
            if audio_file.exists():
                try:
                    metadata = json.loads(metadata_file.read_text(encoding="utf-8"))
                except (FileNotFoundError, json.JSONDecodeError):
                    metadata = {}
                entry = (str(metadata.get("filename") or "reading.wav"), audio_file.read_bytes())
                AUDIO_CACHE[token] = entry
        if not entry:
            self.send_error(404, "That reading is no longer cached")
            return

        name, audio = entry
        start, end = 0, len(audio) - 1
        # Safari will not play media that cannot answer a range request.
        requested = self.headers.get("Range", "")
        match = re.fullmatch(r"bytes=(\d*)-(\d*)", requested.strip()) if requested else None
        if match:
            first, last = match.group(1), match.group(2)
            if first:
                start = min(int(first), len(audio))
                if last:
                    end = min(int(last), len(audio) - 1)
            elif last:  # a suffix range asks for the final N bytes
                start = max(len(audio) - int(last), 0)

        body = audio[start:end + 1]
        self.send_response(206 if match else 200)
        self.send_header("Content-Type", "audio/wav")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Accept-Ranges", "bytes")
        disposition = "attachment" if "download=1" in query.split("&") else "inline"
        self.send_header("Content-Disposition", f'{disposition}; filename="{name}"')
        self.send_header("Cache-Control", "no-store")
        if match:
            self.send_header("Content-Range", f"bytes {start}-{end}/{len(audio)}")
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def do_POST(self) -> None:  # noqa: N802 - stdlib handler API
        stop_match = re.fullmatch(r"/api/tts/jobs/([A-Za-z0-9_-]+)/cancel", self.path)
        if stop_match:
            with TTS_JOBS_LOCK:
                job = TTS_JOBS.get(stop_match[1])
                if job and job['state'] in {'queued', 'running'}:
                    job['stopRequested'] = True
                    job['updatedAt'] = time.time()
                snapshot = dict(job) if job else None
            self._send_json(200 if snapshot else 404, snapshot or {'error': 'Narration queue not found.'})
            return
        if self.path == '/api/image-library':
            self._save_library_image()
            return
        if self.path == '/api/tts/recordings':
            self._tts_recordings()
            return
        if self.path == '/api/tts/availability':
            self._tts_availability()
            return
        if self.path == "/api/tts/jobs":
            self._queue_tts()
            return
        if self.path == "/api/tts/stream":
            self._stream_local_tts()
            return
        if self.path == "/api/tts":
            self._generate_tts()
            return
        if self.path == "/api/tts/lookup":
            self._lookup_tts()
            return
        if self.path == "/api/tts/sample":
            self._tts_sample()
            return
        if self.path == "/api/tts/stitch":
            self._stitch_tts()
            return
        if self.path == "/api/poems":
            self._add_user_poem()
            return
        if self.path.startswith("/api/flux/"):
            upstream_path = self.path.removeprefix("/api/flux")
            if upstream_path == "/generate":
                self._flux_generate()
            elif upstream_path in ALLOWED_POST_PATHS or re.fullmatch(r"/jobs/[A-Za-z0-9_-]+/cancel", upstream_path):
                self._proxy_flux("POST", upstream_path)
            else:
                self.send_error(404, "Unknown FLUX endpoint")
            return
        if self.path.startswith("/api/chat/"):
            upstream_path = self.path.removeprefix("/api/chat")
            if upstream_path in ALLOWED_CHAT_POST_PATHS:
                self._proxy_chat("POST", upstream_path)
            else:
                self.send_error(404, "Unknown model endpoint")
            return
        self.send_error(405, "POST is only supported for the proxies and local TTS")

    def _stitch_tts(self) -> None:
        """Assemble an ordered set of already-saved narration parts."""
        try:
            payload = self._read_json_body()
            if "savedKeys" in payload:
                self._stitch_saved_recordings(payload)
                return
            requests = payload.get("parts", [])
            if not isinstance(requests, list) or not requests or len(requests) > 10000:
                raise ValueError("An ordered list of saved narration parts is required.")
            variants = payload.get("variants") or [{}]
            if not isinstance(variants, list) or not variants or len(variants) > 12 or any(not isinstance(v, dict) for v in variants):
                raise ValueError("Chapter variants must be a short list of voice and model choices.")
            candidates = []
            for part in requests:
                if not isinstance(part, dict):
                    raise ValueError("Every narration part must be an object.")
                choices = []
                for variant in variants:
                    request = {**part, **{field: variant[field] for field in ("voice", "provider", "model") if field in variant}}
                    *_, key, _ = self._tts_request(request)
                    choices.append((key, AUDIO_LIBRARY_PATH / f"{key}.wav"))
                candidates.append(choices)
            # Choose the most complete performance, then fill only its gaps.
            preferred = max(range(len(variants)), key=lambda index: sum(choices[index][1].exists() for choices in candidates))
            keys, paths, selected = [], [], []
            for choices in candidates:
                order = [preferred] + [index for index in range(len(variants)) if index != preferred]
                available = next((choices[index] for index in order if choices[index][1].exists()), None)
                if available is None:
                    raise FileNotFoundError(str(len(paths) + 1))
                key, path = available
                keys.append(key)
                paths.append(path)
                selected.append(choices.index(available))
            stitched_key = stitched_audio_key(keys)
            filename = str(payload.get("filename", "Complete chapter.wav"))
            mix_summary = f"{len(selected) - selected.count(preferred)} alternate parts"
            existing = self._library_audio(stitched_key, filename)
            if existing:
                self._send_tts_audio(*existing, reused=True, mix_summary=mix_summary)
                return
            audio = stitch_wav_files(paths)
            self._send_tts_audio(audio, cache_audio(filename, audio, stitched_key), reused=False, mix_summary=mix_summary)
        except FileNotFoundError as error:
            self._send_json(409, {"error": f"Part {error.args[0]} has not been generated yet."})
        except (ValueError, json.JSONDecodeError, wave.Error) as error:
            self._send_json(400, {"error": str(error)})

    def _stitch_saved_recordings(self, payload: dict) -> None:
        """Join an explicitly selected saved performance, independent of current text."""
        keys = payload.get("savedKeys")
        if (not isinstance(keys, list) or not 1 <= len(keys) <= 10000
                or any(not isinstance(key, str) or not re.fullmatch(r"[a-f0-9]{64}", key) for key in keys)
                or len(set(keys)) != len(keys)):
            raise ValueError("Provide an ordered list of saved recording keys.")
        book_id, title = payload.get("book"), payload.get("title")
        if book_id not in BOOKS_BY_ID or not isinstance(title, str) or not title:
            raise ValueError("Provide a known book and chapter title.")
        paths, identity = [], None
        for index, key in enumerate(keys):
            path = AUDIO_LIBRARY_PATH / f"{key}.wav"
            try:
                record = json.loads(path.with_suffix(".json").read_text())
            except (OSError, ValueError):
                raise ValueError("Saved recording metadata is unavailable.")
            if not isinstance(record, dict):
                raise ValueError("Invalid saved recording metadata.")
            part = re.search(r" - Part (\d+) - ", record.get("filename", ""))
            if (record.get("book") != book_id or record.get("entryTitle") != title
                    or record.get("kind") != "poem" or not part or int(part[1]) != index + 1):
                raise ValueError("Choose consecutive saved parts of the same chapter, starting at part 1.")
            current = tuple(record.get(field) for field in ("provider", "model", "voice"))
            if identity is None:
                identity = current
            if current != identity:
                raise ValueError("Choose saved parts from the same voice and model.")
            if not path.is_file():
                raise FileNotFoundError(str(index + 1))
            paths.append(path)
        key = stitched_audio_key(keys)
        filename = str(payload.get("filename") or f"{title} - Saved chapter.wav")
        existing = self._library_audio(key, filename)
        if existing:
            self._send_tts_audio(*existing, reused=True, mix_summary="saved recording version")
            return
        audio = stitch_wav_files(paths)
        url = cache_audio(filename, audio, key, dict(book=book_id, entryTitle=title, kind="poem",
                          provider=identity[0], model=identity[1], voice=identity[2],
                          savedKeys=keys, sourceVersion="saved"))
        self._send_tts_audio(audio, url, reused=False, mix_summary="saved recording version")

    def _tts_request(self, payload: dict) -> tuple[str, str, str, str, str, str, bool, dict, str, str]:
        title = str(payload.get("title", "")).strip()
        text = str(payload.get("text", "")).strip()
        voice_id = str(payload.get("voice", ""))
        provider = str(payload.get("provider", "local")).strip().lower()
        if provider not in {"local", "gemini"}:
            raise ValueError("provider must be local or gemini.")
        model = str(payload.get("model", DEFAULT_GEMINI_TTS_MODEL)).strip()
        if provider == "gemini" and model not in GEMINI_TTS_MODELS:
            raise ValueError("That Gemini TTS model is not supported.")
        if provider == "local":
            model = LOCAL_TTS_MODEL
        voice = resolve_gemini_voice(voice_id) if provider == "gemini" else resolve_local_voice(voice_id)
        kind = str(payload.get("kind", "poem"))
        speak_title = payload.get("speakTitle", True) is not False
        if not title or not text or not voice or kind not in {"poem", "response"}:
            raise ValueError("title, text, kind, and a supported voice are required.")
        book = self._resolve_book(payload.get("book"))
        book_id = str(book.get("id") or payload.get("book") or "")
        key = audio_library_key(title, text, voice_id, kind, book_id, speak_title, provider, model)
        filename = str(payload.get("filename", "")) or title
        return title, text, voice_id, kind, provider, model, speak_title, book, key, filename

    def _library_audio(self, key: str, filename: str) -> tuple[bytes, str] | None:
        audio_file = AUDIO_LIBRARY_PATH / f"{key}.wav"
        if not audio_file.exists():
            return None
        audio = audio_file.read_bytes()
        return audio, cache_audio(filename, audio, key)

    def _send_tts_audio(self, audio: bytes, audio_path: str, reused: bool, mix_summary: str = "") -> None:
        self.send_response(200)
        self.send_header("Content-Type", "audio/wav")
        self.send_header("Content-Length", str(len(audio)))
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Audio-Path", audio_path)
        self.send_header("X-Audio-Reused", "true" if reused else "false")
        if mix_summary:
            self.send_header("X-Audio-Mix", mix_summary)
        self.end_headers()
        self.wfile.write(audio)

    def _lookup_tts(self) -> None:
        try:
            payload = self._read_json_body()
            *_, key, filename = self._tts_request(payload)
            existing = self._library_audio(key, filename)
            if not existing:
                self._send_json(404, {"error": "No saved reading exists."})
                return
            self._send_tts_audio(*existing, reused=True)
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": str(error)})

    def _tts_recordings(self) -> None:
        """Discover saved performances without selecting a voice or reading WAVs."""
        try:
            payload = self._read_json_body()
            if not isinstance(payload, dict):
                raise ValueError('Provide a book and entry title.')
            book = BOOKS_BY_ID.get(str(payload.get('book', '')))
            title = payload.get('title')
            if not book or not isinstance(title, str) or not title.strip():
                raise ValueError('Provide a known book and entry title.')
            title = title.strip()
            def clean(value):
                return re.sub(r'\s+', ' ', SAFE_FILENAME.sub(' ', value)).strip().strip('.')
            prefix = clean(f"{book.get('poet') or book.get('name')} - {title}")
            # Older browser downloads shortened titles before the server sanitized them.
            def browser_clean(value):
                value = re.sub(r'[\\/:*?"<>|]+', ' ', value)
                value = value.replace('‘', "'").replace('’', "'").replace('“', '').replace('”', '')
                return re.sub(r'\s+', ' ', value).strip()
            legacy_prefix = clean(f"{browser_clean(book.get('poet') or book.get('name'))} - {browser_clean(title)[:70].rstrip('. ')}")
            recordings = []
            for path in AUDIO_LIBRARY_PATH.glob('*.json'):
                if not re.fullmatch(r'[a-f0-9]{64}', path.stem):
                    continue
                try:
                    record = json.loads(path.read_text(encoding='utf-8'))
                except (OSError, ValueError):
                    continue
                if not isinstance(record, dict):
                    continue
                filename = str(record.get('filename', ''))
                if 'entryTitle' in record:
                    matches = (record.get('book') == book['id'] and record['entryTitle'] == title
                               and record.get('kind') == 'poem')
                else:
                    # Older caches only recorded the human-readable filename.
                    matches = any(filename.startswith(p + ' - ') or filename == p + '.wav'
                                  for p in (prefix, legacy_prefix))
                    if ' - commentary - ' in filename:
                        matches = False
                if not matches or not path.with_suffix('.wav').is_file():
                    continue
                recordings.append({'filename': filename,
                    'url': f'/api/tts/audio/{path.stem}/{quote(filename)}',
                    'provider': record.get('provider', ''), 'model': record.get('model', ''),
                    'voice': record.get('voice', '')})
            recordings.sort(key=lambda item: [int(p) if p.isdigit() else p.lower()
                                             for p in re.split(r'(\d+)', item['filename'])])
            self._send_json(200, {'recordings': recordings})
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {'error': str(error)})

    def _tts_availability(self) -> None:
        """Metadata only: never render, read WAV bodies, or require a paid key."""
        try:
            payload = self._read_json_body()
            parts = payload.get('parts') if isinstance(payload, dict) else None
            if not isinstance(parts, list) or not 1 <= len(parts) <= 10000:
                raise ValueError('Provide between 1 and 10000 narration parts.')
            if any(not isinstance(part, dict) for part in parts):
                raise ValueError('Invalid narration part.')
            result = []
            for part in parts:
                *_, key, filename = self._tts_request(part)
                saved = (AUDIO_LIBRARY_PATH / f'{key}.wav').is_file()
                name = SAFE_FILENAME.sub(' ', filename).strip().strip('.')[:120] or 'reading'
                if not name.lower().endswith('.wav'):
                    name += '.wav'
                result.append({'saved': saved, 'url': f'/api/tts/audio/{key}/{quote(name)}' if saved else None})
            self._send_json(200, {'parts': result})
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {'error': str(error)})

    @staticmethod
    def _voice_sample_file(voice: str) -> Path:
        """Named for the voice, stamped with what it says.

        Samples sit outside the role bindings and outside the reading library.
        The stamp is what the passage and the model hash to, so changing either
        renames every file and the old renders read as absent rather than being
        served as though they were current.
        """
        identity = json.dumps(
            {"model": LOCAL_TTS_MODEL, "sample": VOICE_SAMPLE_TEXT},
            ensure_ascii=False, sort_keys=True, separators=(",", ":"),
        )
        stamp = hashlib.sha256(identity.encode("utf-8")).hexdigest()[:8]
        return VOICE_SAMPLES_PATH / f"{voice}-{stamp}.wav"

    def _list_tts_voices(self) -> None:
        global LOCAL_TTS_VOICE_NAMES
        # Discover clones added by the service owner without restarting this app.
        for base in dict.fromkeys(filter(None, (TTS_BASE_URL, TTS_FALLBACK_URL))):
            try:
                with urlopen(base + "/v1/audio/voices", timeout=5) as response:
                    names = json.load(response).get("voices", [])
                if isinstance(names, list) and names:
                    LOCAL_TTS_VOICE_NAMES = {name.lower() for name in names if isinstance(name, str) and name}
                break
            except (URLError, TimeoutError, ValueError):
                continue
        roles = load_tts_voices()
        voices = [
            {
                "name": name,
                "character": character,
                "sampled": self._voice_sample_file(name).exists(),
                "roles": sorted(role for role, bound in roles.items() if bound == name),
            }
            for name, character in [*((name, label) for name, label in LOCAL_TTS_VOICES if name in LOCAL_TTS_VOICE_NAMES), *((name, "Custom voice") for name in sorted(LOCAL_TTS_VOICE_NAMES - {n for n, _ in LOCAL_TTS_VOICES}))]
        ]
        self._send_json(200, {
            "voices": voices,
            "roles": roles,
            "defaults": DEFAULT_TTS_VOICES,
            "sampleText": VOICE_SAMPLE_TEXT,
        })

    def _tts_sample(self) -> None:
        """Read one voice's sample from the library, generating it the first time."""
        try:
            voice = str(self._read_json_body().get("voice", ""))
        except json.JSONDecodeError:
            self._send_json(400, {"error": "The sample request was not valid JSON."})
            return
        if voice not in LOCAL_TTS_VOICE_NAMES:
            self._send_json(400, {"error": f"{voice or 'That voice'} is not a known local voice."})
            return

        sample_file = self._voice_sample_file(voice)
        filename = f"Voice sample - {voice}"
        if sample_file.exists():
            audio = sample_file.read_bytes()
            self._send_tts_audio(audio, cache_audio(filename, audio), reused=True)
            return
        try:
            audio = self._request_local_audio(VOICE_SAMPLE_TEXT, voice, "Measured and natural.")
            VOICE_SAMPLES_PATH.mkdir(exist_ok=True)
            temporary = sample_file.with_suffix(".tmp")
            temporary.write_bytes(audio)
            temporary.replace(sample_file)
            self._send_tts_audio(audio, cache_audio(filename, audio), reused=False)
        except HTTPError as error:
            detail = error.read().decode("utf-8", errors="replace")
            self._send_json(error.code, {"error": f"Local TTS rejected {voice}: {detail[:300]}"})
        except (URLError, TimeoutError) as error:
            self._send_json(502, {"error": f"Local TTS unavailable: {getattr(error, 'reason', error)}"})

    def _assign_tts_voice(self) -> None:
        try:
            payload = self._read_json_body()
        except json.JSONDecodeError:
            self._send_json(400, {"error": "The assignment was not valid JSON."})
            return
        role = str(payload.get("role", ""))
        voice = str(payload.get("voice", ""))
        if role not in DEFAULT_TTS_VOICES:
            self._send_json(400, {"error": f"{role or 'That role'} is not a narration role."})
            return
        if voice not in LOCAL_TTS_VOICE_NAMES:
            self._send_json(400, {"error": f"{voice or 'That voice'} is not a known local voice."})
            return
        roles = load_tts_voices()
        roles[role] = voice
        write_tts_voices(roles)
        self._send_json(200, {"roles": roles})

    def _render_tts(self, payload: dict, api_key: str) -> tuple[bytes, str, bool]:
        # Serialize cache checks with generation so queued and direct requests
        # for the same part cannot incur duplicate charges.
        self._tts_progress(stage="waiting", attempt=0, retryAt=None)
        request = self._tts_request(payload)
        # Lock by cache identity so independent local recordings can run together.
        if request[4] == "gemini":
            lock = TTS_RENDER_LOCK
        else:
            with TTS_KEY_LOCKS_LOCK:
                lock = TTS_KEY_LOCKS.get(request[-2])
                if lock is None:
                    lock = threading.Lock()
                    TTS_KEY_LOCKS[request[-2]] = lock
        with lock:
            return self._render_tts_locked(payload, api_key)

    def _render_tts_locked(self, payload: dict, api_key: str) -> tuple[bytes, str, bool]:
        title, text, voice_id, kind, provider, model, speak_title, book, key, filename = self._tts_request(payload)
        existing = self._library_audio(key, filename)
        if existing:
            return (*existing, True)
        voice = resolve_gemini_voice(voice_id) if provider == "gemini" else resolve_local_voice(voice_id)
        pcm_chunks = []
        audio_format = (1, 2, 24000) if provider == "gemini" else None
        chunks = self._split_tts_text(text, self._narration_part_limit(title, book, provider))
        for index, chunk in enumerate(chunks):
            self._tts_progress(stage="generating", chunk=index + 1, chunks=len(chunks), attempt=1, retryAt=None)
            transcript = (
                f"{title}.\n\n{chunk}"
                if kind == "poem" and speak_title and index == 0
                else chunk
            )
            if provider == "gemini":
                if model.startswith("gemini-3.8-"):
                    pcm_chunks.append(self._request_gemini_38_audio(api_key, voice, transcript, str(book.get("readingNotes", "Measured and natural.")), model))
                else:
                    prompt = self._build_tts_prompt(transcript, index, len(chunks), kind, book)
                    pcm_chunks.append(self._request_gemini_audio(api_key, voice, prompt, model))
            else:
                instruction = str(book.get("readingNotes", "Measured and natural."))
                audio_chunk = self._request_local_audio(transcript, voice, instruction)
                with wave.open(io.BytesIO(audio_chunk), "rb") as wav_file:
                    chunk_format = (wav_file.getnchannels(), wav_file.getsampwidth(), wav_file.getframerate())
                    if audio_format is not None and audio_format != chunk_format:
                        raise ValueError("Local TTS returned inconsistent audio formats across parts.")
                    audio_format = chunk_format
                    pcm_chunks.append(wav_file.readframes(wav_file.getnframes()))

        audio_buffer = io.BytesIO()
        with wave.open(audio_buffer, "wb") as wav_file:
            wav_file.setnchannels(audio_format[0])
            wav_file.setsampwidth(audio_format[1])
            wav_file.setframerate(audio_format[2])
            wav_file.writeframes(b"".join(pcm_chunks))
        audio = audio_buffer.getvalue()
        audio_path = cache_audio(filename, audio, key, {
            'book': book['id'], 'entryTitle': re.sub(r' · Part \d+$', '', title),
            'kind': kind, 'provider': provider, 'model': model, 'voice': voice_id,
        })
        return audio, audio_path, False

    def _queue_tts(self) -> None:
        try:
            parts = self._read_json_body().get("parts")
            if not isinstance(parts, list) or not 1 <= len(parts) <= 10000:
                raise ValueError("Provide between 1 and 10000 narration parts.")
            if any(not isinstance(part, dict) for part in parts):
                raise ValueError("Invalid narration part.")
            requests = [self._tts_request(part) for part in parts]
            api_key = self.headers.get("X-Gemini-API-Key", "").strip() or GEMINI_API_KEY
            if any(request[4] == "gemini" for request in requests) and not api_key:
                self._send_json(401, {"error": "A Gemini API key is required."})
                return
            identity = hashlib.sha256(json.dumps([r[-2] for r in requests]).encode()).hexdigest()
            with TTS_JOBS_LOCK:
                for job in TTS_JOBS.values():
                    if job["identity"] == identity and job["state"] in {"queued", "running"}:
                        snapshot = dict(job)
                        break
                else:
                    for job_id in list(TTS_JOBS):
                        if len(TTS_JOBS) < 64:
                            break
                        if TTS_JOBS[job_id]["state"] in {"done", "failed"}:
                            del TTS_JOBS[job_id]
                    if len(TTS_JOBS) >= 64:
                        raise ValueError("Narration queue is full. Please try again later.")
                    job_id = secrets.token_hex(16)
                    job = dict(id=job_id, identity=identity, state="queued", total=len(parts), completed=0, reused=0, error="", stage="queued", updatedAt=time.time())
                    TTS_JOBS[job_id] = job
                    TTS_EXECUTOR.submit(self._run_tts_job, job_id, parts, api_key)
                    snapshot = dict(job)
            self._send_json(202, snapshot)
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": str(error)})

    def _tts_progress(self, **fields) -> None:
        job_id = getattr(self, "_tts_job_id", None)
        if job_id:
            with TTS_JOBS_LOCK:
                job = TTS_JOBS[job_id]
                if job.get('stopRequested'):
                    raise TTSStopped('Narration stopped. Saved parts are kept; generate missing parts to resume.')
                if fields.get("stage") != job.get("stage") or fields.get("attempt") != job.get("attempt"):
                    fields["stageStartedAt"] = time.time()
                part_index = getattr(self, "_tts_part_index", None)
                if part_index is not None:
                    job["partProgress"][part_index].update(fields)
                    fields["part"] = part_index + 1
                job.update(fields, updatedAt=time.time())

    def _run_tts_job(self, job_id: str, parts: list[dict], api_key: str) -> None:
        self._tts_job_id = job_id
        with TTS_JOBS_LOCK:
            TTS_JOBS[job_id]["state"] = "running"
        try:
            parallel = len(parts) > 1 and all(self._tts_request(part)[4] == "local" for part in parts)
            if parallel:
                with TTS_JOBS_LOCK:
                    TTS_JOBS[job_id]["partProgress"] = [dict(stage="queued") for _ in parts]
                pending = iter(enumerate(parts))
                pending_lock = threading.Lock()
                halted = threading.Event()

                def worker():
                    handler = copy.copy(self)
                    while True:
                        with pending_lock:
                            if halted.is_set():
                                return
                            with TTS_JOBS_LOCK:
                                if TTS_JOBS[job_id].get("stopRequested"):
                                    raise TTSStopped("Narration stopped. Saved parts are kept; generate missing parts to resume.")
                            item = next(pending, None)
                        if item is None:
                            return
                        index, part = item
                        handler._tts_part_index = index
                        try:
                            handler._tts_progress(stage="starting", chunk=0, chunks=0, attempt=0, retryAt=None)
                            _, _, reused = handler._render_tts(part, api_key)
                            with TTS_JOBS_LOCK:
                                job = TTS_JOBS[job_id]
                                job["partProgress"][index].update(stage="done")
                                job["completed"] += 1
                                job["reused"] += int(reused)
                        except Exception:
                            halted.set()
                            with TTS_JOBS_LOCK:
                                TTS_JOBS[job_id]["partProgress"][index].update(stage="failed")
                            raise

                # Separate pool avoids deadlocking the executor that runs jobs.
                # LOCAL_TTS_SLOTS limits provider traffic across all batches.
                with ThreadPoolExecutor(max_workers=min(LOCAL_TTS_BATCH_WORKERS, len(parts)), thread_name_prefix="tts-parts") as executor:
                    futures = [executor.submit(worker) for _ in range(min(LOCAL_TTS_BATCH_WORKERS, len(parts)))]
                    for future in futures:
                        future.result()
            else:
                for index, part in enumerate(parts):
                    self._tts_progress(part=index + 1, stage="starting", chunk=0, chunks=0, attempt=0, retryAt=None)
                    _, _, reused = self._render_tts(part, api_key)
                    with TTS_JOBS_LOCK:
                        job = TTS_JOBS[job_id]
                        job["completed"] += 1
                        job["reused"] += int(reused)
            with TTS_JOBS_LOCK:
                TTS_JOBS[job_id].update(state="done", stage="done", updatedAt=time.time())
        except Exception as error:
            if isinstance(error, TTSStopped):
                message = str(error)
            elif isinstance(error, HTTPError):
                message = tts_provider_error(error, api_key)
            elif isinstance(error, TTSGenerationError):
                message = str(error)
            elif isinstance(error, (URLError, TimeoutError, ConnectionError, HTTPException)):
                message = "The narration provider timed out or lost its connection after retries."
            else:
                message = "Narration failed. Check the provider and retry."
            with TTS_JOBS_LOCK:
                job = TTS_JOBS[job_id]
                job.update(state="failed", stage="failed", retryAt=None, updatedAt=time.time(),
                           error=f"Stopped at part {job.get('part', 1)} of {len(parts)}. {message} "
                           "Choose Generate missing parts to resume; saved parts will be reused.")
        finally:
            self._tts_job_id = None

    def _generate_tts(self) -> None:
        provider = "local"
        api_key = self.headers.get("X-Gemini-API-Key", "").strip() or GEMINI_API_KEY
        try:
            payload = self._read_json_body()
            provider = self._tts_request(payload)[4]
            if provider == "gemini" and not api_key:
                self._send_json(401, {"error": "A Gemini API key is required."})
                return
            audio, audio_path, reused = self._render_tts(payload, api_key)
            self._send_tts_audio(audio, audio_path, reused=reused)
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": str(error)})
        except HTTPError as error:
            detail = error.read().decode("utf-8", errors="replace")
            # Provider errors can echo credentials. Never send those to the UI.
            if provider == "gemini":
                detail = detail.replace(api_key, "[redacted]") if api_key else detail
                if "CONSUMER_SUSPENDED" in detail:
                    detail = "The configured Gemini API consumer has been suspended by Google. Enter a working Gemini API key or restore access for its Google project."
            self._send_json(error.code, {"error": f"TTS request failed: {detail}"})
        except (URLError, TimeoutError) as error:
            reason = getattr(error, "reason", str(error))
            self._send_json(502, {"error": f"TTS unavailable: {reason}"})
        except Exception as error:  # Keep proxy failures legible to the browser.
            self.log_error("Local TTS failure: %s", error)
            self._send_json(502, {"error": f"Could not generate narration: {error}"})

    @staticmethod
    def _narration_part_limit(title: str, book: dict, provider: str) -> int:
        if provider != "gemini":
            return 5000
        chapter_title = re.sub(r" · Part \d+$", "", title)
        configured = book.get("geminiNarrationPartLimits", {}).get(chapter_title)
        return min(configured, 5000) if type(configured) is int and configured >= 1800 else 5000

    @staticmethod
    def _split_tts_text(text: str, limit: int = 850) -> list[str]:
        """Prefer paragraphs, sentences, then lines/words within the hard limit.

        Keep boundary order in sync with splitNarrationText in app.js.
        """
        if limit < 1:
            raise ValueError("Invalid narration limit")
        remaining = text.replace("\r\n", "\n").replace("\r", "\n").strip()
        chunks = []
        boundaries = (r"\n[ \t]*\n+", r"[.!?][\"'”’»\)\]]*\s+", r"\n", r"\s+")
        while len(remaining) > limit:
            split_at = 0
            for boundary in boundaries:
                for match in re.finditer(boundary, remaining):
                    end = match.start() + len(match.group().rstrip())
                    if end > limit:
                        break
                    if end > 0:
                        split_at = end
                if split_at:
                    break
            # A word longer than the limit is the only forced character split.
            split_at = split_at or limit
            chunks.append(remaining[:split_at].strip())
            remaining = remaining[split_at:].strip()
        if remaining:
            chunks.append(remaining)
        return chunks

    @staticmethod
    def _resolve_book(book_id) -> dict:
        """Map the requested book id onto a books.json record; never trust the raw value."""
        return BOOKS_BY_ID.get(str(book_id or ""), DEFAULT_BOOK)

    @staticmethod
    def _build_tts_prompt(transcript: str, index: int, total: int, kind: str, book: dict) -> str:
        continuation = "This is a continuation; preserve the established voice and cadence." if index else ""
        poet = str(book.get("poet", "the poet"))
        if kind == "response":
            return f"""Synthesize speech for an exact reading of literary commentary. Do not speak these directions.

AUDIO PROFILE: A clear, warm literary companion explaining {poet} to an attentive reader.
DIRECTOR'S NOTES: Natural and conversational, with intelligent emphasis and an unhurried explanatory cadence. Make quotations distinct without theatrical exaggeration. Do not add, omit, summarize, explain, or repeat any words. {continuation}
TRANSCRIPT — SPEAK ONLY THE TEXT BELOW
{transcript}"""
        reader_profile = str(book.get("readerProfile", f"A seasoned reader of poetry performing {poet} for an attentive audience."))
        reading_scene = str(book.get("readingScene", "A quiet reading room with close, warm acoustics."))
        reading_notes = str(book.get("readingNotes", "Measured and contemplative, but never flat. Use intelligent rhetorical emphasis, natural breath at line endings, and slightly longer pauses between stanzas."))
        return f"""Synthesize speech for an exact literary reading. Do not speak these directions.

AUDIO PROFILE: {reader_profile}
SCENE: {reading_scene}
DIRECTOR'S NOTES: {reading_notes} Do not add, omit, explain, modernize, or repeat any words. {continuation}
TRANSCRIPT — SPEAK ONLY THE TEXT BELOW
{transcript}"""

    def _open_local_speech(self, text: str, voice: str, instruction: str = "", response_format: str = "pcm"):
        if not text.strip() or len(text) > 20000:
            raise ValueError("Local speech requires 1–20,000 characters.")
        body = json.dumps({"input": text, "voice": voice, "instructions": instruction,
                           "language": "English", "model": "tts-1", "response_format": response_format}).encode()
        for index, base in enumerate(dict.fromkeys(filter(None, (TTS_BASE_URL, TTS_FALLBACK_URL)))):
            try:
                return urlopen(Request(base + "/v1/audio/speech", data=body,
                                       headers={"Content-Type": "application/json"}, method="POST"), timeout=300)
            except HTTPError:
                raise
            except (URLError, TimeoutError):
                if index or not TTS_FALLBACK_URL or TTS_FALLBACK_URL == TTS_BASE_URL:
                    raise

    def _request_local_audio(self, text: str, voice: str, instruction: str = "") -> bytes:
        # PCM avoids Qwen's unspecified streaming WAV length in saved recordings.
        with LOCAL_TTS_SLOTS, self._open_local_speech(text, voice, instruction) as response:
            pcm = response.read()
        if not pcm or len(pcm) % 2:
            raise ValueError("Local TTS returned incomplete PCM audio.")
        output = io.BytesIO()
        with wave.open(output, "wb") as audio:
            audio.setparams((1, 2, 24000, 0, "NONE", "not compressed"))
            audio.writeframes(pcm)
        return output.getvalue()

    def _stream_local_tts(self) -> None:
        try:
            payload = self._read_json_body()
            voice = str(payload.get("voice", "ryan")).lower()
            voice = load_tts_voices().get(voice, voice)
            fmt = str(payload.get("response_format", "pcm"))
            if fmt not in {"wav", "pcm"}:
                raise ValueError("response_format must be wav or pcm.")
            with LOCAL_TTS_SLOTS, self._open_local_speech(str(payload.get("input", "")), voice,
                    str(payload.get("instructions", "")), fmt) as response:
                self._stream_proxy_response(response)
        except (ValueError, json.JSONDecodeError) as error:
            self._send_json(400, {"error": str(error)})
        except HTTPError as error:
            self._send_json(error.code, {"error": "Local speech request was rejected."})
        except (URLError, TimeoutError) as error:
            self._send_json(502, {"error": "Local speech service is unavailable."})

    def _request_gemini_38_audio(self, api_key: str, voice: str, transcript: str, style: str, model: str) -> bytes:
        # 3.8 speaks the transcript verbatim; directions belong in metadata.
        body = {
            "model": model, "store": False,
            "input": [{"type": "user_input", "content": [{
                "type": "text", "text": transcript,
                "annotations": [{"type": "speech_metadata", "style": style}],
            }]}],
            "response_format": {"type": "audio", "mime_type": "audio/wav", "sample_rate": 24000},
            "generation_config": {
                "max_output_tokens": GEMINI_TTS_MAX_OUTPUT_TOKENS,
                "speech_config": [{"voice": voice}],
            },
        }
        request = Request(
            "https://generativelanguage.googleapis.com/v1beta/interactions",
            data=json.dumps(body).encode(),
            headers={"Content-Type": "application/json", "x-goog-api-key": api_key},
            method="POST",
        )
        # No automatic paid retries: a failed part can be explicitly resumed.
        self._pace_gemini_request()
        self._tts_progress(stage="generating", retryAt=None)
        with urlopen(request, timeout=300) as response:
            result = json.load(response)
        if result.get("status") != "completed":
            raise ValueError("Gemini did not complete the narration. Saved parts are kept.")
        audio_blocks = [content for step in result.get("steps", [])
                        if step.get("type") == "model_output"
                        for content in step.get("content", [])
                        if content.get("type") == "audio" and content.get("data")]
        if not audio_blocks:
            raise ValueError("Gemini returned no narration audio.")
        chunks = []
        for block in audio_blocks:
            audio = base64.b64decode(block["data"], validate=True)
            with wave.open(io.BytesIO(audio), "rb") as wav_file:
                if (wav_file.getnchannels(), wav_file.getsampwidth(), wav_file.getframerate()) != (1, 2, 24000):
                    raise ValueError("Gemini returned an unexpected audio format.")
                chunks.append(wav_file.readframes(wav_file.getnframes()))
        return b"".join(chunks)

    def _request_gemini_audio(self, api_key: str, voice: str, prompt: str, model: str = DEFAULT_GEMINI_TTS_MODEL) -> bytes:
        """Request 24 kHz mono PCM from Gemini's steerable TTS model."""
        body = json.dumps({
            "contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {
                "responseModalities": ["AUDIO"],
                # The API otherwise chooses a much smaller default budget. Audio
                # consumes about 25 tokens/second, so that default can end a
                # perfectly valid response midway through the supplied text.
                "maxOutputTokens": GEMINI_TTS_MAX_OUTPUT_TOKENS,
                "speechConfig": {
                    "voiceConfig": {
                        "prebuiltVoiceConfig": {"voiceName": voice}
                    }
                },
            },
        }).encode()
        request = Request(
            f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent",
            data=body,
            headers={"Content-Type": "application/json", "x-goog-api-key": api_key},
            method="POST",
        )
        def decode(payload):
            candidates = payload.get("candidates") or []
            candidate = candidates[0] if candidates else {}
            finish_reason = candidate.get("finishReason", "unknown")
            if finish_reason == "MAX_TOKENS":
                raise TTSGenerationError("Gemini exhausted its audio output budget before finishing the text.")
            if payload.get("promptFeedback", {}).get("blockReason") or finish_reason in {
                "SAFETY", "PROHIBITED_CONTENT", "BLOCKLIST", "RECITATION", "SPII",
            }:
                raise TTSGenerationError("Gemini declined to narrate this passage. Try a different provider.")
            parts = candidate.get("content", {}).get("parts", [])
            audio_part = next((part.get("inlineData") for part in parts if part.get("inlineData")), None)
            if not audio_part or not audio_part.get("data"):
                raise TTSRetryableError("Gemini returned no narration audio after retries.")
            audio = base64.b64decode(audio_part["data"], validate=True)
            if audio.startswith(b"RIFF"):
                with wave.open(io.BytesIO(audio), "rb") as wav_file:
                    if (wav_file.getnchannels(), wav_file.getsampwidth(), wav_file.getframerate()) != (1, 2, 24000):
                        raise TTSGenerationError("Gemini returned an unexpected audio format.")
                    frames = wav_file.getnframes()
                    audio = wav_file.readframes(frames)
                    if len(audio) != frames * 2:
                        raise TTSRetryableError("Gemini returned incomplete narration audio after retries.")
            if not audio or len(audio) % 2:
                raise TTSRetryableError("Gemini returned incomplete narration audio after retries.")
            return audio

        return self._request_tts_with_retries(request, decode, timeout=600 if len(prompt) > 4000 else 180)

    def _pace_gemini_request(self) -> None:
        # Generation already holds TTS_RENDER_LOCK, including direct requests.
        global GEMINI_TTS_NEXT_REQUEST_AT
        delay = GEMINI_TTS_NEXT_REQUEST_AT - time.monotonic()
        if delay > 0:
            self._tts_progress(stage="pacing", retryAt=time.time() + delay)
            time.sleep(delay)
        GEMINI_TTS_NEXT_REQUEST_AT = time.monotonic() + GEMINI_TTS_REQUEST_INTERVAL

    def _request_tts_with_retries(self, request, decode, timeout: int) -> bytes:
        """Bound transient retries; permanent provider rejections stop immediately."""
        max_attempts = 4
        for attempt in range(6):
            self._pace_gemini_request()
            self._tts_progress(stage="generating", attempt=attempt + 1, maxAttempts=max_attempts, retryAt=None, retryReason=None)
            try:
                with urlopen(request, timeout=timeout) as response:
                    payload = json.load(response)
                return decode(payload)
            except HTTPError as error:
                if error.code == 429:
                    max_attempts = 6
                if error.code not in {408, 429, 500, 502, 503, 504} or attempt + 1 >= max_attempts:
                    raise
                delay = min(300, 60 * 2 ** attempt) if error.code == 429 else min(60, 15 * 2 ** attempt)
                retry_after = error.headers.get("Retry-After", "") if error.headers else ""
                if retry_after:
                    try:
                        delay = max(delay, float(retry_after))
                    except ValueError:
                        try:
                            delay = max(delay, parsedate_to_datetime(retry_after).timestamp() - time.time())
                        except (ValueError, TypeError, OverflowError):
                            pass
                if delay > 900:
                    error.close()
                    raise TTSGenerationError("Gemini requested a cooldown longer than 15 minutes. Resume missing parts later; saved audio is kept.")
                delay = max(1, delay)
                reason = "Provider rate limit" if error.code == 429 else "Temporary provider error"
                error.close()
            except (URLError, TimeoutError, ConnectionError, HTTPException,
                    json.JSONDecodeError, binascii.Error, wave.Error, EOFError, TTSRetryableError) as error:
                if attempt + 1 >= max_attempts:
                    if isinstance(error, (json.JSONDecodeError, binascii.Error, wave.Error, EOFError)):
                        raise TTSGenerationError("Gemini repeatedly returned an incomplete or invalid audio response.") from error
                    raise
                delay = (5, 15, 30, 30, 30)[attempt]
                reason = "Incomplete response" if isinstance(error, (ValueError, wave.Error, EOFError)) else "Provider connection interrupted"
            self._tts_progress(stage="retrying", retryAt=time.time() + delay, retryReason=reason, maxAttempts=max_attempts)
            time.sleep(delay)

    def _send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode()
        self._send_proxy_response(status, {"Content-Type": "application/json"}, body)

    def _flux_generate(self) -> None:
        """Attach the negative prompt for SDXL, and strip it for backends that refuse it."""
        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length) if length else b""
        try:
            payload = json.loads(body or b"{}")
        except json.JSONDecodeError:
            payload = None
        if not isinstance(payload, dict):
            self._send_json(400, {"success": False, "error": "The generation request was not valid JSON."})
            return

        negative = str(payload.get("negative_prompt") or "").strip() or NEGATIVE_PROMPT
        sdxl = flux_supports_negative_prompt()
        payload = {**payload, "negative_prompt": negative if sdxl else None}
        status, headers, response = self._flux_upstream(payload)
        # A backend swapped since the last check can still be handed a field it
        # rejects. Spend one retry without it rather than lose the generation.
        # Only the codes FLUX uses to refuse a field count; a 5xx or a bad key
        # says nothing about which backend is loaded.
        if sdxl and status in (400, 422):
            remember_flux_backend(False)
            status, headers, response = self._flux_upstream({**payload, "negative_prompt": None})
        self._send_proxy_response(status, headers, response)

    def _flux_upstream(self, payload: dict) -> tuple[int, dict, bytes]:
        api_key = FLUX_API_KEY or self.headers.get("X-API-Key", "")
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        if api_key:
            headers["X-API-Key"] = api_key
        request = Request(f"{FLUX_BASE_URL}/generate", data=json.dumps(payload).encode(), headers=headers, method="POST")
        try:
            with urlopen(request, timeout=45) as response:
                return response.status, dict(response.headers), response.read()
        except HTTPError as error:
            return error.code, dict(error.headers), error.read()
        except (URLError, TimeoutError) as error:
            reason = getattr(error, "reason", str(error))
            body = json.dumps({"success": False, "error": f"FLUX server unavailable: {reason}"}).encode()
            return 502, {"Content-Type": "application/json"}, body

    def _proxy_flux(self, method: str, upstream_path: str) -> None:
        api_key = FLUX_API_KEY or self.headers.get("X-API-Key", "")
        self._proxy(
            f"{FLUX_BASE_URL}{upstream_path}",
            method,
            {"X-API-Key": api_key} if api_key else {},
            # FLUX status can wait on backend telemetry even while the host
            # is reachable. Allow that work to finish before declaring it offline.
            timeout=30 if upstream_path == "/status" else 45,
            unavailable=lambda reason: {"success": False, "error": f"FLUX server unavailable: {reason}"},
        )

    def _proxy_chat(self, method: str, upstream_path: str) -> None:
        """Fail over before streaming, resolving model IDs on the selected server."""
        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length) if length else None
        headers = {"Accept": self.headers.get("Accept", "application/json")}
        if body is not None:
            headers["Content-Type"] = self.headers.get("Content-Type", "application/json")
        backends = list(dict.fromkeys(url for url in (VLLM_BASE_URL, VLLM_FALLBACK_URL) if url))
        for index, base_url in enumerate(backends):
            try:
                request_body = body
                if method == "POST" and VLLM_FALLBACK_URL:
                    # Saved conversations may carry the other backend's model ID.
                    # A short discovery timeout also catches an offline primary.
                    with urlopen(f"{base_url}/v1/models", timeout=5) as models_response:
                        models = json.load(models_response).get("data", [])
                    model_ids = [model["id"] for model in models if model.get("id")]
                    if not model_ids:
                        raise URLError("No available models")
                    payload = json.loads(body or b"{}")
                    if payload.get("model") not in model_ids:
                        payload["model"] = model_ids[0]
                    request_body = json.dumps(payload).encode()
                request = Request(f"{base_url}{upstream_path}", data=request_body, headers=headers, method=method)
                response = urlopen(request, timeout=5 if method == "GET" else CHAT_TIMEOUT)
            except HTTPError as error:
                with error:
                    error_body = error.read()
                if index + 1 < len(backends) and (error.code == 429 or error.code >= 500):
                    continue
                self._send_proxy_response(error.code, error.headers, error_body)
                return
            except (URLError, TimeoutError, ConnectionError) as error:
                if index + 1 < len(backends):
                    continue
                reason = getattr(error, "reason", str(error))
                self._send_json(502, {"error": {"message": f"Model servers unavailable: {reason}"}})
                return
            except (ValueError, KeyError, TypeError) as error:
                self._send_json(502, {"error": {"message": f"Invalid model request or discovery response: {error}"}})
                return
            # Never retry once response headers or tokens have reached the browser.
            with response:
                self._stream_proxy_response(response)
            return

    def _proxy(self, url: str, method: str, extra_headers: dict, timeout: int, unavailable, stream: bool = False) -> None:
        length = int(self.headers.get("Content-Length", "0"))
        body = self.rfile.read(length) if length else None
        headers = {"Accept": self.headers.get("Accept", "application/json"), **extra_headers}
        if body is not None:
            headers["Content-Type"] = self.headers.get("Content-Type", "application/json")

        request = Request(url, data=body, headers=headers, method=method)
        try:
            with urlopen(request, timeout=timeout) as response:
                if stream:
                    self._stream_proxy_response(response)
                else:
                    self._send_proxy_response(response.status, response.headers, response.read())
        except HTTPError as error:
            self._send_proxy_response(error.code, error.headers, error.read())
        except (URLError, TimeoutError) as error:
            reason = getattr(error, "reason", str(error))
            message = json.dumps(unavailable(reason))
            self._send_proxy_response(502, {"Content-Type": "application/json"}, message.encode())

    def _stream_proxy_response(self, response) -> None:
        """Forward the body chunk by chunk, without Content-Length, to keep tokens live."""
        self.send_response(response.status)
        self.send_header("Content-Type", response.headers.get("Content-Type", "application/octet-stream"))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        try:
            while True:
                chunk = response.read1(8192)
                if not chunk:
                    break
                self.wfile.write(chunk)
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError):
            pass  # The reader stopped the response or closed the page.

    def _send_proxy_response(self, status: int, headers, body: bytes) -> None:
        self.send_response(status)
        self.send_header("Content-Type", headers.get("Content-Type", "application/octet-stream"))
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", headers.get("Cache-Control", "no-store"))
        self.end_headers()
        self.wfile.write(body)


def main() -> None:
    server_config = CONFIG.get("server", {})
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default=server_config.get("host", "0.0.0.0"), help="bind address")
    parser.add_argument("--port", type=int, default=server_config.get("port", 8000), help="port")
    args = parser.parse_args()

    os.chdir(BASE_DIR)
    server = ThreadingHTTPServer((args.host, args.port), PoetryRequestHandler)
    print(f"Serving John Donne poems at http://{args.host}:{args.port}")
    print(f"Proxying image requests to {FLUX_BASE_URL}")
    print(f"Proxying model requests to {VLLM_BASE_URL}")
    server.serve_forever()


if __name__ == "__main__":
    main()
